version: '3'

services:
    docker-mysql:
        container_name: docker-mysql
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'q'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'q'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            #- //d/docker/mysql/shared/data:/var/lib/mysql
            - ./shared/data:/var/lib/mysql
            # Names our volume